name: Docker Compose Train and Test

on:
  push:
    branches:
      - main

jobs:
  compose:
    runs-on: ubuntu-latest
    
    outputs:
      skip: ${{ steps.skip_check.outputs.skip }}

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

    - name: Check for Skip Keyword
      id: skip_check
      run: |
        echo "Checking for skip keyword in commit message..."
        if echo '${{ github.event.head_commit.message }}' | grep -q "\[skip ci\]"; then
          echo "::set-output name=skip::true"
        else
          echo "::set-output name=skip::false"
        fi
      
    - name: Docker Compose Up Train
      if: steps.skip_check.outputs.skip == 'false'
      run: docker-compose up train
      
    - name: Docker Compose Up Test
      if: steps.skip_check.outputs.skip == 'false'
      run: docker-compose up test

    - name: Commit and Push Generated Files
      if: steps.skip_check.outputs.skip == 'false'
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        git remote set-url origin https://${{ secrets.PERSONAL_ACCESS_TOKEN }}:x-oauth-basic@github.com/ganand2021/ml-workflows.git
        git add .
        git diff-index --quiet HEAD || git commit -m "Add generated files from Docker Compose services [skip ci]"
        git push origin main
